uid: rules_tools:open_reminder
label: Open Reminder
description: This will trigger on a change to an Item in a Group. If the change is different from a "good state" (or the same as the "good state" if the match is inverted) and it remains that state for a specified amount of time it will call another script and reschedule to repeat until the Item returns or a do not distrurb period is entered.
configDescriptions:
  - name: groupTriggers
    type: TEXT
    context: item
    filterCriteria:
      - name: type
        value: Group
    label: Group of Triggering Items
    description: Group whose members should trigger this rule.
    required: true
  - name: goodState
    type: TEXT
    label: Good State
    description: Any state different from this will cause the rule to run.
    required: true
  - name: invert
    type: BOOLEAN
    label: Invert
    description: Inverts the match so an state that is the same as Good State will cause the rule to run.
    defaultValue: false
    required: false
  - name: defaultTimeout
    type: TEXT
    label: Default Initial Timeout
    description: If a triggering Item doesn't have a timeout metadata, the default initial time to wait before calling the script the first time. Use "PTVdWhXmYsZz" format where d=days, h=hours, m=minutes, s=seconds, and z=milliseconds (e.g. "PT2d5s" = two days, five seconds).
    defaultValue: PT15m
    required: true
  - name: timeoutMetadata
    type: TEXT
    label: Default Item Initial Timeout Metadata
    description: Item metadata namespace to check for a custom initial timeout for the triggering Item. Use "PTVdWhXmYsZz" format where d=days, h=hours, m=minutes, s=seconds, and z=milliseconds (e.g. "PT2d5s" = two days, five seconds).
    defaultValue: rem_time
    required: false
  - name: repeatPeriod
    type: TEXT
    label: Repeat Period
    description: How often to repeat calling the alert rule after the initial call while the Item remains in a "not good" state.  Use "PTVdWhXmYsZz" format where d=days, h=hours, m=minutes, s=seconds, and z=milliseconds (e.g. "PT2d5s" = two days, five seconds). If left blank no repeat is performed.
    defaultValue: ''
    required: false
  - name: alertRuleUID
    type: TEXT
    context: rule
    label: Alert Rule
    description: Rule called after the initial timeout and every repeat period thereafter as long as the Item remains in a "not good" state.
  - name: dndStart
    label: Do Not Distrub Start Time
    description: The start of the time where alerts are not allowed. Alerts are only sent outside of the time between this time and the alerting end time. If both are the same, alerts will be sent any time.
    type: TEXT
    required: false
    context: time
    defaultValue: 00:00
  - name: dndEnd
    label: Do Not Disturb End Time
    description: The end of the time where alerts are not allowed. Alerts are only sent outside of the alerting start time and alerting end time. If both are the same, alerts will be send any time.
    type: TEXT
    required: false
    context: time
    defaultValue: 00:00
triggers:
  - id: "1"
    configuration:
      groupName: "{{groupTriggers}}"
    type: core.GroupStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript;version=ECMAScript-2021
      script: >
        var {loopingTimer} = require('openhab_rules_tools');

        var logger = log('rules_tools.'+ruleUID);


        // Rule Properties

        var goodState = "{{goodState}}";

        var defaultTimeout = "{{defaultTimeout}}";

        var timeoutMetadata = "{{timeoutMetadata}}";

        var alertRuleUID = "{{alertRuleUID}}";

        var repeatPeriod = "{{repeatPeriod}}";

        var dndStart = "{{dndStart}}";

        var dndEnd = "{{dndEnd}}";

        var noAlertPeriod = (dndStart == dndEnd);

        var runRule = (curr) => { return ({{invert}}) ? (curr == goodState) : (curr != goodState); };


        // If you edit this rule, run it manually to clear out the cache or else

        // errors will occur complaining about the context being closed.

        if(this.event === undefined) {
          logger.info('Resetting looping timers');
          cache.put(ruleUID+'_timers', null);
        }

        else {
          var timers = cache.get(ruleUID+'_timers', () => new Map());
          var item = event.itemName;
          var state = event.itemState.toString();

          // This returns the function called by the LoopingTimer. LoopingTimer will
          // reschedule the timer based on what the function passed to it returns. If
          // a duration is returned it will be reschuled for that time into the future.
          // If null is returned the looping stops.
          var sendAlertGenerator = (alertItem) => {
            return () => {
              const currState = items.getItem(alertItem).state;
              logger.debug('Timer expired for ' + alertItem + ', calling alert rule');

              var alert = true;
              if(!noAlertPeriod && time.toZDT().isBetweenTimes(dndStart, dndEnd)) {
                logger.debug('Currently in the do not disturb period between ' + dndStart
                             + ' and ' + dndEnd + '. Alerting will end now.');
                alert = false;
              }

              if(currState == goodState) {
                logger.debug('Item is now in the good state.');
                alert = false;
              }

              if(alert) {
                logger.debug('It is not between the do not disturb times and ' + alertItem
                             + ' is still not ' + goodState);
                rules.runRule(alertRuleUID, { 'alertItem': alertItem, 'currState': currState }, true);
                if(repeatPeriod == '' || repeatPeriod === null) {
                  logger.debug('No repeat period is defined, will not repeat');
                  timers.delete(alertItem);
                  return null;
                }
                else {
                  return repeatPeriod;
                }
              }
              else {
                logger.debug('No more alerts are scheduled.')
                timers.delete(alertItem);
                return null;
              }
            }
          };

          logger.debug('Running door alert rule with: \n' +
                       '  item:           ' + item + '\n' +
                       '  state:          ' + state + '\n' +
                       '  goodState:      ' + goodState + '\n' +
                       '  defaultTimeout: ' + defaultTimeout + '\n' +
                       '  repeatPeriod:   ' + repeatPeriod + '\n' +
                       '  dndStart:       ' + dndStart + '\n' +
                       '  dndEnd:         ' + dndEnd + '\n' +
                       '  noAlertPeriod:  ' + noAlertPeriod + '\n' +
                       '  alertRuleUID:   ' + alertRuleUID);

          // Returned to goodState and timer exists, cancel the looping timer
          if(state == goodState && timers.has(item)) {

            logger.debug(item + ' has returned to the normal state of ' + goodState + ', canceling the timer if it exists.');
            timers.get(item).cancel();
            timers.delete(item);

          }

          // Item changed to a not goodState, create a looping timer if one doesn't already exist
          else if(runRule(state)) {
            logger.debug(item + ' is not the good state of ' + goodState);

            // There shouldn't be a Timer if the Item just changed to the goodState, log to show
            // something went wrong.
            if(timers.has(item)) {
              logger.warn(item + ' state is now ' + state + ' but an alert timer already exists! This should not have happened!');
            }
            // Schedule a looping timer to start at the initial timeout (from metadata) and repeat
            // on repeatPeriod
            else {
              const metadata = items.getItem(item).getMetadataValue(timeoutMetadata);
              const timeout = (metadata) ? metadata : defaultTimeout;
              timers.set(item, new loopingTimer.LoopingTimer());
              logger.debug('Starting alerting timer for ' + timeout + ' for ' + item);
              timers.get(item).loop(sendAlertGenerator(item), timeout);
            }
          }
        }
    type: script.ScriptAction
