uid: rules_tools:presence_sim
label: Simulates presence by commanding Items based on historic states
description: Triggers periodically when a given Item is ON and plays back the states of Items stored in persistence.
configDescriptions:
  - name: enableSim
    type: TEXT
    context: item
    filterCriteria:
      - name: type
        value: Switch
    label: Enable Simulation
    required: true
    description: When not ON, the simulation rule will run (e.g. when Presence is OFF presence simulation will run).
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 0/${minutes} * * * ? *
    type: timer.GenericCronTrigger
conditions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: ${enableSim}
      state: ON
      operator: "!="
    type: core.ItemStateCondition
actions:
  - inputs: {}
    id: "3"
    label: Playback ${simItems}'s states from ${days} days ago
    configuration:
      type: application/vnd.openhab.dsl.rule
      script: >-
        val logName = "Presence Sim"

        ${simItems}.members
                   .forEach[i | 
                           val hState = i.historicState(now.minusDays(${days}))
                           if(hState === null) 
                               logWarn(logName, i.name + " does not have a historic state for " + ${days} + "days ago.")
                           else {
                             logInfo(logDebug, "Commanding " + i.name + " to " + hState.state)
                             if(i.state != hState.state)
                                 i.sendCommand(hState.state.toString)
                             else
                                 logDebug(logName, light.name + " " + " is already " + hState.state)
                           }
                       ]
    type: script.ScriptAction

