triggers:
  - id: "1"
    configuration:
      thingUID: mqtt:broker:argus
      status: ONLINE
    type: core.ThingStatusChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript
      script: |
        var Log = Java.type("org.openhab.core.model.script.actions.Log");

        var openHAB_name = "remote";

        Log.logInfo("MQTT_EB", "Publishing online message");
        var mqtt = actions.get("mqtt", "mqtt:broker:argus");
        mqtt.publishMQTT(openHAB_name + "/status", "ONLINE", true);
    type: script.ScriptAction
