triggers:
  - id: "1"
    configuration:
      thingUID: mqtt:broker:broker
      channelUID: mqtt:broker:broker:dadsoh_out
    type: core.ChannelEventTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript
      script: >-
        var logger =
        Java.type("org.slf4j.LoggerFactory").getLogger("org.openhab.model.script.MQTT_EB");


        var parts = event.event.split("#");

        var topic = parts[0];

        var state = parts[1];

        parts = topic.split("/");

        var item_name = parts[2];

        var event_type = parts[3];


        logger.info("Received EB message: type = " + event_type + " item = " + item_name + " state/cmd = " + state);


        if(items[item_name] === undefined) {
          logger.warn(item_name + " does not exist!");
        }

        else {
          (event_type == "command") ? events.sendCommand(item_name, state) : events.postUpdate(item_name, state);
        }
    type: script.ScriptAction
